import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import AppProvider from "@/Providers/AppProvider";

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <body className={`${vazirmatn.variable} antialiased`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
